# Generated by Django 4.2.2 on 2023-06-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='biomarked',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart')], max_length=50),
        ),
        migrations.AddField(
            model_name='biomarked',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producttype'),
        ),
    ]
