# Generated by Django 4.2.2 on 2023-06-30 08:00

from django.db import migrations



def load_roles(apps, schema_editor):
    Role = apps.get_model("user", "Role")

    role_superadmin = Role(id=2, name='IS_SUPERADMIN')
    role_superadmin.save()

    role_admin = Role(id=1, name='IS_ADMIN')
    role_admin.save()

    role_is_member = Role(id=3, name='IS_MEMBER')
    role_is_member.save()



def delete_roles(apps, schema_editor):
    Role = apps.get_model("user", "Role")
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_roles'),
    ]

    operations = [
        migrations.RunPython(load_roles, delete_roles),

    ]
