# Generated by Django 4.2.2 on 2023-06-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230630_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='user.role'),
        ),
    ]
