# Generated by Django 4.2.2 on 2023-07-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_member_created_at_billmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billmember',
            name='paid_member',
        ),
    ]
