# Generated by Django 4.2.2 on 2023-07-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_billmember_paid_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmember',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='billmember',
            constraint=models.UniqueConstraint(fields=('position',), name='unique_position'),
        ),
    ]
