# Generated by Django 4.2.2 on 2023-07-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_remove_billmember_unique_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmember',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
