# Generated by Django 4.2.2 on 2023-07-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_billmember_position'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billmember',
            table='billmembers',
        ),
    ]
